# Generated by Django 3.2 on 2021-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComapnyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('totalEmployees', models.IntegerField()),
                ('addreess', models.TextField()),
                ('emailAddress', models.CharField(max_length=50)),
            ],
        ),
    ]
