# Generated by Django 3.2 on 2021-07-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_comapnymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComapnyModel',
            new_name='CompanyModel',
        ),
    ]
